site_name: Aqua Standard Specification
site_description: Specification for Aqua programming language.
site_author: Aqua Standard Specification contributers

repo_url: 'https://github.com/artelephantb/aqua-standard-specification/'
edit_uri: 'blob/main/spec/'

theme: readthedocs

docs_dir: 'spec/'
nav:
  - About: 'index.md'

extra_css:
  - 'styling/extra.css'

copyright: '&copy; 2026, licensed under <a href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a><img src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;"><img src="https://mirrors.creativecommons.org/presskit/icons/sa.svg" alt="" style="max-width: 1em;max-height:1em;margin-left: .2em;">'
